# Generated by Django 4.2.16 on 2024-10-04 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_visits', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_visits', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryPageTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DictionarySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_visits', models.IntegerField(default=1)),
                ('dictionary_medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='visitors.dictionarymedium')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_visits', models.IntegerField(default=1)),
                ('dictionary_page_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='visitors.dictionarypagetitle')),
            ],
        ),
        migrations.CreateModel(
            name='PeakTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(db_index=True, unique=True)),
                ('total_visits', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_visits', models.IntegerField(default=1)),
                ('dictionary_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='visitors.dictionarysource')),
            ],
        ),
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_ip', models.CharField(max_length=64, unique=True)),
                ('salt', models.CharField(max_length=16)),
                ('user_cookie', models.CharField(blank=True, max_length=255, null=True)),
                ('browser_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_visits', models.IntegerField(default=1)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.country')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_campaigns', to='visitors.campaign')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_media', to='visitors.medium')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_pages', to='visitors.page')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_sources', to='visitors.source')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_visits', models.IntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='visitors.location')),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_visits', models.IntegerField(default=1)),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_systems', to='visitors.operatingsystem')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_visits', models.IntegerField(default=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_types', to='visitors.device')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='Traffic_Source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.trafficsource'),
        ),
        migrations.AddField(
            model_name='country',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.devicetype'),
        ),
        migrations.AddField(
            model_name='country',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='visitors.location'),
        ),
        migrations.AddField(
            model_name='country',
            name='operating_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.os'),
        ),
        migrations.AddField(
            model_name='country',
            name='peak_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.peaktime'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.region'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_visits', models.IntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='visitors.location')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='visitors.region')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='dictionary_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='visitors.dictionarycampaign'),
        ),
    ]
