# Generated by Django 4.2.16 on 2024-10-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('audio', models.FileField(upload_to='uploads/')),
                ('animated_video', models.FileField(blank=True, null=True, upload_to='animated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
